In [1]:
import pandas as pd

In [2]:
fmat_file = '../ppi_ml/data/apms/featmat_humap'
fmat = pd.read_csv(fmat_file)

In [3]:
cols = fmat.columns.tolist()
score_cols = cols[1:]
id_cols = ['ID1','ID2']

In [5]:
fmat[['ID1','ID2']] = fmat['ID'].str.split(' ',expand=True)
fmat.drop('ID', axis=1, inplace=True)

In [7]:
fmat = fmat[id_cols+score_cols]

In [8]:
fmat.head()

,ID1,ID2,ext_Dm_guru,ext_Hs_malo,entropy_orig9k,zscore_orig9k,nwdscore_orig9k,plate_zscore_orig9k,uPeps_orig9k,neg_ln_pval,...,neg_ln_pval_treiber_hygeo_gt4,pair_count_treiber_hygeo_gt4,neg_ln_pval_youn_hygeo,pair_count_youn_hygeo,neg_ln_pval_youn_hygeo_gt2,pair_count_youn_hygeo_gt2,neg_ln_pval_youn_hygeo_gt4,pair_count_youn_hygeo_gt4,neg_ln_pval_treiber_hygeo_gt2,pair_count_treiber_hygeo_gt2
0,100101267,100288406,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
1,100101267,100294276,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
2,100101267,100507680,0.0,0,0.0,0.0,0.0,0.0,0.0,2.520528,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
3,100101267,100507686,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
4,100101267,100507703,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0

In [9]:
ogs_only = fmat[fmat['ID1'].str.startswith(('ENOG','KOG')) & fmat['ID2'].str.startswith(('ENOG','KOG'))]

In [12]:
ogs_only.to_csv('../ppi_ml/data/apms/featmap_humap_euNOGs.csv', index=False, na_rep='')
ogs_only.to_pickle('../ppi_ml/data/apms/featmap_humap_euNOGs.pkl')